
logPretty: false
services:
  - name: pjkOrder
    server:
      - 121.40.59.24:8068
    domain: pjk-order.api.yunchuangfu.com
    enableRatelimit: false
    enableCache: true
    cacheKey: ""
    loadBalance: random
    whiteIps: 127.0.0.1
  - name: roseMember
    server:
      - 121.40.210.184:8070
    domain: rose-member.api.yunchuangfu.com
    enableRatelimit: true
    enableCache: false